### ISSUE TITLE
Create Report From Scanning Multiple Files

### ISSUE THREAD

**Issue by kev1nme1er** [Breakthrough/DVR-Scan#10] opened 2019-03-16 17:34 UTC
This is a feature request, not a bug.  The surveillance NVR records many files to a single folder for each day.  I would like the ability to process all files in a single folder and receive a report at the end of which files had motion in them.  It would also be ideal for DVR-Scan to have a delete option to delete any files without motion, or to somehow mark them (maybe rename) so that they can easily be deleted.

**Comment by Breakthrough** [comment] 2019-03-17 20:40
The batch processing is a good idea, and is a duplicate of #5.

I don't want to make DVR-Scan modify any input files, but could make it output a list/CSV file for each file that has motion detected.  Then one could write a script to look at all of the CSV files, and if they have more than just a header row, you know there was motion in the video (otherwise it is safe to delete).

Is this an acceptable solution for you?  If so I can close this as a duplicate of #5.

**Comment by kev1nme1er** [comment] 2019-03-17 21:49
To be honest, I created my own solution using PowerShell, but I think a log file listing the files with motion would be beneficial as my DVR generates a new file every 5 minutes so there are a lot of them to scan through.

Cheers!
Kevin



________________________________

**Comment by Breakthrough** [comment] 2019-03-17 23:31
Hi @kev1nme1er;

Gotcha, that makes sense.  I guess this is more similar to a kind of "report" function then.

How about something like that, which generates a CSV file containing a list of all scanned video files, and how many motion events were detected (as well as other possible statistics in the future, e.g. average motion event length)?

Thanks!

**Comment by kev1nme1er** [comment] 2019-03-18 01:25
That would be a great option.  Not sure how feasible it is, but being able to apply a sensitivity would also be a huge benefit as the wind moving a lawn sign is enough to detect motion.   In any case, this is a great utility and as I use it more, I may see other enhancement opportunities.

Do you have an account somewhere for donations or do you plan on selling this at some point?  I'm always willing to pay for useful software.


Cheers!
Kevin



________________________________

**Comment by Breakthrough** [comment] 2020-08-30 17:49
Hi @kev1nme1er;

Sorry for the delayed response.  No plans as of yet for donations or monetization, currently have a lot on the go with my career.  However I'm always open to new opportunities or ideas.  I may sign up for the Github Sponsors program, but want to be cautious that I cannot offer paid support or any kind of for-profit development (at least not in my current position).

I'm currently sorting out creating a distribution for Windows again, after which I can return to looking at feature development like this.  Supporting multiple input files is definitely something that's still on my radar, I just still have a lot of refactor and quality-of-life improvements to address on the project before adding new features.

Many thanks for the suggestions and feedback, will keep you posted for sure!

**Comment by Breakthrough** [comment] 2020-08-30 17:52
Possible duplicate of #5, revisit when in progress.

**Closed** 2022-02-15 04:34 UTC
Labels: feature, status: duplicate
