### ISSUE TITLE
Performance: to scan 1 month of recording it requires 15 days!

### ISSUE THREAD

**Issue by bhupeshrawal** [Breakthrough/DVR-Scan#29] opened 2020-06-14 04:05 UTC
I am scanning video files each of 1 minute and it is taking 25 to 30 second for every file. Is there something available to speed up this process as otherwise it is very difficult using this tool for any real purpose. Pls advise.

**Comment by Breakthrough** [comment] 2021-02-06 23:56
Could you share some more details about your system (os/python ver/packages)?  How did you install OpenCV/numpy?  What resolution/framerate is your input video?

One way to get a quick speed up is to set `-df 2`. Let me know if this helps!

**Comment by Breakthrough** [comment] 2021-05-14 02:43
The next few releases of DVR-Scan will emphasize performance.  Closing as duplicate of #51.

**Closed by Breakthrough** 2021-05-14 02:43 UTC
