### ISSUE TITLE
Keep same input format in output file

### ISSUE THREAD

**Issue by angelferre** [Breakthrough/DVR-Scan#49] opened 2021-03-11 08:01 UTC
Hi,
I am working with long video files (up to 72 h) for plate recognition, so I use DVR-scan to have shorter videos only with vehicles. 
I try to have well compressed videos, such as 720p, 100-200 kbps, 8 fps, H.264 or H.265, so I usually have videos of 1-2 GB per day.
Now I am obtaining let's say 1-2 h video from an input of 24 h, that's ok, but output size is double than the 24 h original.
Is there a way in DVR-scan to keep the same input settings when generating the output file? Or at least choosing some output settings, in order not to re-transcode the whole file with ffmpeg?
Thanks

**Comment by Breakthrough** [comment] 2021-03-11 15:02
Hi @angelferre;

This will be addressed in DVR-Scan v2.0 (see #42 for more information).
The goal is indeed to have better integration with ffmpeg to allow stream
copying or high quality re-encoding.  Right now DVR-Scan uses the OpenCV
VideoWriter class which has a lot of limitations.  Integration with ffmpeg
would also allow keeping original audio (#27) as well as allow for some
parallelization by running the actual encoding process in a separate
thread/background process.

I will close this as a duplicate of #42, but feel free to continue the
discussion there.

Thanks for the suggestion!

**Comment by angelferre** [comment] 2021-03-12 09:00
Thanks for your answer

I will follow the thread in #42 as suggested

 



 



 

Angel Ferre Giménez

General Manager

M:      +34 627 48 25 20 

E:        ***@***.***> ***@***.*** 

@Sant Cugat Business Park

Av. Via Augusta, 15-25

08174 Sant Cugat del Vallès (Barcelona)

 

De: Brandon Castellano ***@***.***> 
Enviado el: dijous, 11 de març de 2021 16:03
Para: Breakthrough/DVR-Scan ***@***.***>
CC: angelferre ***@***.***>; Mention ***@***.***>
Asunto: Re: [Breakthrough/DVR-Scan] Keep same input format in output file (#49)

 

Hi @angelferre;

This will be addressed in DVR-Scan v2.0 (see #42 for more information).
The goal is indeed to have better integration with ffmpeg to allow stream
copying or high quality re-encoding. Right now DVR-Scan uses the OpenCV
VideoWriter class which has a lot of limitations. Integration with ffmpeg
would also allow keeping original audio (#27) as well as allow for some
parallelization by running the actual encoding process in a separate
thread/background process.

I will close this as a duplicate of #42, but feel free to continue the
discussion there.

Thanks for the suggestion!

**Closed** 2021-05-14 01:57 UTC
Labels: status: duplicate
