### ISSUE TITLE
Analyzing multiple videos with multiple output videos

### ISSUE THREAD

**Issue by myscho15** [Breakthrough/DVR-Scan#57] opened 2021-08-11 10:28 UTC
Hallo,

i have question - is posible in DVR SCAN make command to analyze multiple videos and then every analyzed video will have outputs in separated video? 

In folder have i videos: from 001 to 040.avi ... and standard is one output 001-040output.avi, I want to make command wich give me 40 outpus videos... 

Thank you and sorry for misstakes, my Ennglish is verry bad.

**Comment by Breakthrough** [comment] 2021-08-12 02:47
I'll be looking into this in the future to support glob inputs, but for now take a look at Issue #5.

There are some workarounds posted there which can help by using a shell/cmd script, e.g. for Windows:

    for /F %i in ('dir *.avi /b') do dvr-scan -i %i

And for Linux/Mac:

    for f in "*"
    do
        dvr-scan -i $f
    done

Closing as duplicate of #5; feel free to continue the discussion there if you have any further questions :)

**Closed by Breakthrough** 2021-08-12 02:47 UTC
